mini_insta/urls.py
# File: urls.py
# Author: Anna LaPrade (alaprade@bu.edu), 09/23/2025
# Description: the url patterns for the mini_insta

from django.urls import path
from .views import *

# generic view for authentication/authorization
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',  ShowAllView.as_view(), name="show_all_profiles"),
    path('profile/<int:pk>', ProfileDetailView.as_view(), name='show_profile'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='show_post'),
    path('profile/create_post', CreatePostView.as_view(), name='create_post'),
    path('profile/update', UpdateProfileView.as_view(), name='update_profile'),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('post/<int:pk>/update', UpdatePostView.as_view(), name='update_post'),
    path('profile/<int:pk>/followers', ShowFollowersDetailView.as_view(), name='show_followers'),
    path('profile/<int:pk>/following', ShowFollowingDetailView.as_view(), name='show_following'),
    path('profile/feed', PostFeedListView.as_view(), name="show_feed"),
    path('profile/search', SearchView.as_view(), name='search'),

    # authorization-realted URLS:
    path('login/', auth_views.LoginView.as_view(template_name='mini_insta/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view( template_name='mini_insta/logout.html'), name='logout'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('profile/<int:pk>/follow', FollowView.as_view(), name='follow'),
    path('profile/<int:pk>/delete_follow', DeleteFollowView.as_view(), name='delete_follow'),
    path('post/<int:pk>/like', LikeView.as_view(), name='like'),
    path('post/<int:pk>/delete_like', DeleteLikeView.as_view(), name='delete_like'),
    path('post/<int:pk>/comment/', CreateCommentView.as_view(), name='create_comment'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='delete_comment'),
]

mini_insta/models.py
# File: models.py
# Author: Anna LaPrade (alaprade@bu.edu), 09/23/2025
# Description: the models and their attributes for the mini_insta app

from django.db import models
from django.contrib.auth.models import User # for authentication1

# Create your models here.

# mini-insta profile model 
class Profile(models.Model):
    '''Encapsulate the data of a Profile by an user.'''

    # define the data attributed to this object 
    username = models.TextField(blank=True)
    display_name = models.TextField(blank=True)
    profile_image_url = models.URLField(blank=True)
    bio_text = models.TextField(blank=True)
    join_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # get all Posts associated with a Profile
    def get_all_posts(self):
        '''Return a QuerySet of Posts on this Profile'''
        posts = Post.objects.filter(profile=self).order_by('-timestamp')
        return posts
    
    # gets all Followers associated with a Profile 
    def get_followers(self):
        ''' Returns list of followers associated with this profile '''
        follower_query = Follower.objects.filter(profile=self)
        followers = [follower.follower_profile for follower in follower_query]

        return followers
    
    # gets the number of Followers associated with a Profile 
    def get_num_followers(self):
        '''Returns the number of Followers associated with a profile'''
        return Follower.objects.filter(profile=self).count()
    
    # gets all Profiles another Profile follows 
    def get_following(self):
        ''' Returns list of followed profies associated with this profile '''
        following_query = Follower.objects.filter(follower_profile=self)
        following = [follows.profile for follows in following_query]

        return following
    
    # gets the number all Profiles another Profile follows 
    def get_num_following(self):
        '''Returns the number of followed profiles associated with a profile'''
        return Follower.objects.filter(follower_profile=self).count()

    # gets the feed for a particular Profile
    def get_post_feed(self):
        following_profiles = self.get_following() + [self]

        # if they're aren't any, return none
        if not following_profiles:
            return Post.objects.none()
        
        # newest first
        return Post.objects.filter(profile__in=following_profiles).order_by('-timestamp')

    
    # string formatting
    def __str__(self):
        ''' return a strig representation of this model instance '''
        return f'{self.display_name}, username: {self.username}'
    

# mini-insta post model, one profile to many posts
class Post(models.Model):
    '''Encapsulate the idea of a Post on a Profile'''

    # data attribute for the Posts
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    caption = models.TextField(blank=False)

    # get all photos associated with a Post
    def get_all_photos(self):
        '''Return a QuerySet of Posts on this Profile'''
        photos = Photo.objects.filter(post=self).order_by('-timestamp')
        return photos
    
    # get all comments associated with a Post
    def get_all_comments(self):
        '''Return a QuerySet of comments on this Profile'''
        comments = Comment.objects.filter(post=self).order_by('-timestamp')
        return comments
    
    # get all likes associated with a Post
    def get_all_likes(self):
        '''Return a QuerySet of Likes on this Profile'''
        likes = Like.objects.filter(post=self).order_by('-timestamp')
        return likes
    
    # get the number of likes associated with a Post
    def get_like_count(self):
        """Return the number of likes for this post."""
        return Like.objects.filter(post=self).count()
    

    # string representation of a Post
    def __str__(self):
        ''' return a string representation of this Post instance '''
        return f'{self.caption} by {self.profile.username}'
    

# mini-insta photo model, one post to many photos
class Photo(models.Model):
    '''Encapsulate the idea of a Photo within a Post'''

    # data attribute for the Photo
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image_url = models.URLField(blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    image_file = models.ImageField(blank=True)
    
    # string representation of a Photo
    def __str__(self):
        if self.image_url:
            image_source = self.image_url
        elif self.image_file:
            image_source = self.image_file.name
        else:
            image_source = 'No image'

        return f'Photo for "{self.post.caption}" - {image_source}'

    # get the image URL
    def get_image_url(self):
        '''Returns the URL of the image. '''

        if self.image_url:
            return self.image_url
        elif self.image_file:
            return self.image_file.url
        else:
            return None
        


# mini-insta Follow model
class Follower(models.Model):
    '''Encapsulate the idea of a Follower of a Profile'''

    # data attribute for the Photo
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile")
    follower_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="follower_profile")
    timestamp = models.DateTimeField(auto_now=True)

    # string representation of a Follower
    def __str__(self):
        ''' return a string representation of this Follower instance '''
        return f'{self.follower_profile.username} follows {self.profile.username}'
    
   

class Comment(models.Model):
    '''Encapsulate the idea of a Comment about a Post'''

    # data attribute for the Comments
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    text = models.TextField(blank=False)
    
    # string representation of a Comment
    def __str__(self):
        ''' return a string representation of this Comment instance '''
        return f'{self.text} by {self.profile.username} on {self.post.caption}'
    

class Like(models.Model):
    '''Encapsulate the idea of a Like about a Post'''

    # data attribute for the Likes
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

    # string representation of a Like
    def __str__(self):
        ''' return a string representation of this Comment instance '''
        return f'{self.profile.username} liked {self.post.caption} on {self.timestamp}'


    

mini_insta/templates/mini_insta/base.html
<!-- File: base.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 09/23/2025 -->
<!-- Description: the base html file that others extend for the mini_insta app -->

<!-- allows to load in static data -->
{% load static %}

<html>
    <!-- Heading, linked stylesheet -->
    <head>
        <title>Emo Insta</title>
        <link rel="stylesheet" href="{% static 'styles-mini-insta.css' %}">
            
    </head>

    <body>
        <!-- basic navagtion bar -->
        <header class="navbar">
            <h1 class="logo">Emo Insta</h1>

            <div class="navbar-user-actions">
                <!-- only add logout option if user is logged in -->
                {% if request.user.is_authenticated %}
                    <span class="navbar-user">User: {{ request.user }}</span>
        
                    <form method="post" action="{% url 'logout' %}" class="navbar-form">
                        {% csrf_token %}
                        <button type="submit" class="navbar-button">Logout</button>
                    </form>
                {% else %}
                    <!-- Only show "Not Logged In" + create profile + log in buttons if not logged in-->
                    <span class="navbar-user">Not Logged In</span>
                    <a href="{% url 'login' %}" class="navbar-button">Login</a>
                    <a href="{% url 'create_profile' %}" class="navbar-button">Create Profile</a>
                {% endif %}
            </div>

            <nav>
                <ul class="nav-links">
                    <li><a href="{% url 'show_all_profiles' %}">Show All</a></li>
                </ul>
            </nav>
        </header>

        <!-- page-specific content goes here, with wrapper for better margin delegation -->
        <div class="content-wrapper">
            {% block content %}
            {% endblock %}
        </div>


        <!-- bottom navigation bar -->
        <nav class="bottom-nav">
    

            <!-- all Profiles -->
            <a href="{% url 'show_all_profiles' %}">All Profiles</a> 

            <!-- search page -->

            {% if request.user.is_authenticated %}
                <a href="{% url 'search' %}">Search</a>

            {% endif %}

            {% if profile and request.user.is_authenticated %}
                <!-- create Post -->
                <a href="{% url 'create_post' %}">Create Post</a>

                

                
            {% endif %}

            <!-- profile page, show only if user is logged in and has a profile -->
            {% if request.user.is_authenticated %}
                {% with request.user.profile_set.first as my_profile %}
                    {% if my_profile %}
                        <a href="{% url 'show_profile' my_profile.pk %}">My Profile</a>
                         <!-- if we have a profile, link Home to the feed -->
                        <a href="{% url 'show_feed' %}">Show Feed</a>
                    {% endif %}
                {% endwith %}
            {% endif %}
        </nav>

        <!-- footer with music embed :D -->
        <footer class="site-footer">
            <p>Listen to MCR while browsing:</p>
            <!-- I did steal this from the Spotify website,,, they have embedding code :) -->
            <iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/artist/7FBcuc1gsnv6Y1nwFtNRCb?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        </footer>
    </body>
 
</html>

mini_insta/templates/mini_insta/create_post_form.html
<!-- File: create_post_form.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 09/30/2025 -->
<!-- Description: the template for the form that allows post creation for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<!-- form formatting -->
    <div class="form-container">
        <h1>Create a new Post on "{{ profile.username }}"</h1>

        <!-- takes form from forms.py, adds a URL feild and cancel/submit buttons -->
        <form method="POST" class="form_style" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="form-field">
                {{ form.caption.label_tag }}
                {{ form.caption }}
            </div>

            <!-- add extra image field -->
            <div class="form-field">
                <label for="id_image_files" class="upload-button-label">Upload Images</label>
                <input type="file" name="image_files" id="id_image_files" multiple hidden>
            </div>

            <!-- cancel and submit buttons -->
            <div class="form-buttons">
                <button type="submit">Submit</button>
                <!-- generates URL to go back to profile -->
                <a href="{% url 'show_profile' profile.pk %}">
                    <button type="button" class="cancel-button">Cancel</button>
                </a>
            </div>
        </form>
    </div>

{% endblock %}

mini_insta/templates/mini_insta/create_profile_form.html
<!-- File: create_profile_form.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 10/23/2025 -->
<!-- Description: the template for the form that allows profile/user creation for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<h1 class="page-title">Create Your Account and Profile</h1>

<form method="post" enctype="multipart/form-data" class="create-profile-form">
  {% csrf_token %}

  <!-- user form stuff -->
  <fieldset>
    <legend>Account Info</legend>
    {{ user_form.as_p }}
  </fieldset>

  <!-- profile form stuff -->
  <fieldset>
    <legend>Profile Info</legend>
    {{ profile_form.as_p }}
  </fieldset>

  <button type="submit" class="update-post-button">Create Account</button>
</form>

{% endblock %}

mini_insta/templates/mini_insta/delete_post_form.html
<!-- File: delete_post_form.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 10/5/2025 -->
<!-- Description: the template that allows to delete posts for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<div class="form-container">
    <h3>Are you sure you want to delete this post?</h3>
    <p>
        {{post}}
    </p>

    <!-- form to submit the delete request-->
    <form method="POST" class="form_style">
        {% csrf_token %}

        <!-- delete and cancel buttons-->
        <div class="form-buttons">
            <button type="submit">Delete</button>

            <a href="{% url 'show_post' post.pk %}">
                <button type="button" class="cancel-button">Cancel</button>
            </a>

        </div>
    </form>

</div>

{% endblock %}

mini_insta/templates/mini_insta/logout.html
<!-- File: logout.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 10/23/2025 -->
<!-- Description: the template for the form that allows logout for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<div class="form-container" style="text-align:center;">
    <h1 class="logout-message">You've been logged out from Emo Insta</h1>

    <!-- log in again button -->
    <div style="margin-top:15px;">
        <a href="{% url 'login' %}" class="navbar-button">Login again?</a>
    </div>
</div>

{% endblock %}

mini_insta/templates/mini_insta/search.html
<!-- File: search.html -->
<!-- Author: Anna LaPrade (alaprade@bu.edu), 10/15/2025 -->
<!-- Description: the html template to show the search form -->

{% extends 'mini_insta/base.html' %}

{% block content %}
    <div class="form-container">

        <h2>Search</h2>
        
        <!-- bring in a search form for user input -->
        <form action="{% url 'search' %}" method="get" class="search-form">
            <input type="text" name="query" placeholder="Search Profiles or Posts" required>
            <button type="submit">Search</button>
        </form>

    </div>
{% endblock %}

mini_insta/templates/mini_insta/search_results.html
<!-- File: search_results.html -->
<!-- Author: Anna LaPrade (alaprade@bu.edu), 10/15/2025 -->
<!-- Description: the html template to show all search results -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<!-- basic info  -->
<h2>Search Results for "{{ query }}"</h2>

<br>

<!-- Resulting profiles -->
<h3>Matching Profiles</h3>

<br>

<!-- loop through potenital matches if they exist-->
{% if matching_profiles %}
    <main class="grid-container">
        <!-- display all matching profiles -->
        {% for prof in matching_profiles %}
        <div class="profile-card">
    
            <!-- generates profile URL -->
            <a href="{% url 'show_profile' prof.pk %}"> 
                <img src="{{ prof.profile_image_url }}" alt="{{ prof.username }}'s profile picture" class="profile-image">     
            </a>
    
            <h2>{{ prof.display_name }}</h2>
            <p>Username: {{ prof.username }}</p>
    
        </div>
    {% endfor %}
    </main>
{% else %}
    <p>No profiles found.</p>
{% endif %}

<br>

<!-- Display resulting posts -->
<h3>Matching Posts</h3>

<br>

<!-- check if any posts match -->
{% if posts %}
    <!-- display all matching posts -->
    {% for post in posts %}

        <div class="post-content-search">

            <h4>{{ post.profile.username }}</h4>

            <p>{{ post.caption }}</p>

            <!-- dislay the first photo of the post-->
            {% if post.get_all_photos.first %}
                <img src="{{ post.get_all_photos.first.get_image_url }}" alt="Post photo" class="post-photo">
            {% endif %}
            
            <p>{{ post.timestamp }}</p>
        </div>

    {% endfor %}
{% else %}
    <p>No posts found.</p>
{% endif %}
{% endblock %}

mini_insta/templates/mini_insta/show_all_profiles.html
<!-- File: show_all_profiles.html -->
<!-- Author: Anna LaPrade (alaprade@bu.edu), 09/23/2025 -->
<!-- Description: the html template to show all profiles for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

    <h1>All Profiles</h1>

    <!-- displays profiles in a grid -->
    <main class="grid-container">
        <!-- interate through each profile and add appropriate details to a card -->
        {% for profile in profiles %}
        <div class="profile-card">

            <!-- generates profile URl-->
            <a href="{% url 'show_profile' profile.pk %}"> 
                <img src="{{ profile.profile_image_url }}" alt="{{ profile.username }}'s profile picture" class="profile-image">
            </a>

            <h2>{{ profile.display_name }}</h2>
            
            <p>Username: {{ profile.username }}</p>
        </div>
        {% endfor %}
    </main>

{% endblock %}

mini_insta/templates/mini_insta/show_feed.html
<!-- File: show_feed.html -->
<!-- Author: Anna LaPrade (alaprade@bu.edu), 10/15/2025 -->
<!-- Description: the html template to show all the posts on a given profile's feed -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

    <!-- loop through posts in following list-->
    {% for post in posts %}
            <div class="post-box">
                <div class="post-content">
                    <div class="post-header">
                        <!-- clickable profile image -->
                        <a href="{% url 'show_profile' post.profile.pk %}">
                            <img src="{{ post.profile.profile_image_url }}" 
                                alt="{{ post.profile.username }}'s profile picture" 
                                class="tiny-profile-pic">
                        </a>
                        
                        <!-- user and diplay name-->
                        <h1>@{{ post.profile.username }}  --  {{ post.profile.display_name }}</h1>
                    </div>

                    <!-- time stamp for entire post-->
                    <p class="post-timestamp">posted at {{ post.timestamp }}</p>

                        <!-- display the first photot of the post and its timestamp if it exists-->
                        {% if post.get_all_photos.first %}
                            <div class="photo-container">
                                <a href="{% url 'show_post' post.pk %}">
                                    <img src="{{ post.get_all_photos.first.get_image_url }}" alt="Post photo" class="post-photo">
                                </a>
                                
                            </div>
                            <p class="photo-timestamp">photo posted at {{ post.get_all_photos.first.timestamp }}</p>
                        {% endif %}
                    
                    <p class="post-caption">{{ post.caption }}</p>

                </div>

            <br>

            <!-- summary of likes, display at least 1 name if liked by >= 1-->
            <div class="like-summary">
                {% if post.get_all_likes.count > 0 %}
                    Liked by <span class="like-user">@{{post.get_all_likes.0.profile.username }}</span>
                    {% if post.get_all_likes.count > 1 %}
                        and <span class="like-count">{{ post.get_all_likes.count|add:"-1" }} others</span>
                    {% endif %}
                {% else %}
                    No likes yet
                {% endif %}
            </div>

            <!-- like button for feed -->
            <div class="like-buttons">
                <!-- show if user is logged in and it's not their post -->
                {% if request.user.is_authenticated and request.user != post.profile.user %}
                    <!-- if user has liked it, show unlike button -->
                    {% if post.liked_by_user %}
                        <!-- Unlike button -->
                        <form method="post" action="{% url 'delete_like' post.pk %}" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{% url 'show_feed' %}">
                            <button type="submit" class="navbar-button">Unlike</button>
                        </form>
                    <!-- otherwise, show like button -->
                    {% else %}
                        <!-- Like button -->
                        <form method="post" action="{% url 'like' post.pk %}" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{% url 'show_feed' %}">
                            <button type="submit" class="navbar-button">Like</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>

            <!-- loop through comments and display them-->
            <div class="comment-box-detail">
                {% for comment in post.get_all_comments %}
                    <div class="comment-box">
                        <h4>{{ comment.profile.username }}</h4>
                        <p class="comment-text">{{ comment.text }}</p>
                        <p class="comment-timestamp">{{ comment.timestamp }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}



{% endblock %}

mini_insta/templates/mini_insta/show_followers.html
<!-- File: show_followers.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 10/15/2025 -->
<!-- Description: the template that allows detail follower view for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

    <!-- back to profile navigation -->
    <a href="{% url 'show_profile' profile.pk %}" class="navbar-button">← Back to Profile</a>

    <h1>Followers</h1>

    <main class="grid-container">
        <!-- loop throught followers-->
        {% for follower in profile.get_followers %}

        <div class="profile-card">
        
            <!-- grab the profile care -->
            <a href="{% url 'show_profile' follower.pk %}"> 
                <img src="{{ follower.profile_image_url }}" alt="{{ follower.username }}'s profile picture" class="profile-image"> 
            </a>

            <h2>{{ follower.display_name }}</h2>
            <p>Username: {{ follower.username }}</p>

        </div>

        <!-- if no followers, display that there's none -->
        {% empty %}
        <p>No followers yet.</p>
        {% endfor %}
   
    </main>

{% endblock %}

mini_insta/templates/mini_insta/show_following.html
<!-- File: show_following.html -->
<!--  Author: Anna LaPrade (alaprade@bu.edu), 10/15/2025 -->
<!-- Description: the template that allows detail following view for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<a href="{% url 'show_profile' profile.pk %}" class="navbar-button">← Back to Profile</a>

    <h1>Following</h1>

    <br>

    <main class="grid-container">
        <!-- loop through the profiles they are followed by -->
        {% for followed in profile.get_following %}

        <!-- display profile card -->
        <div class="profile-card">

            <a href="{% url 'show_profile' followed.pk %}"> 
                <img src="{{ followed.profile_image_url }}" alt="{{ followed.username }}'s profile picture" class="profile-image">
            </a>

            <h2>{{ followed.display_name }}</h2>
            <p>Username: {{ followed.username }}</p>

        </div>

        <!-- if no followers, display that there's none -->
        {% empty %}
        <p>Following no profiles yet.</p>
        {% endfor %}

    </main>

{% endblock %}

mini_insta/templates/mini_insta/show_profile.html
<!-- File: show_profile.html -->
<!-- Author: Anna LaPrade (alaprade@bu.edu), 09/23/2025 -->
<!-- Description: the html template to show details of one profile for the mini_insta app -->

<!-- extend from the base template -->
{% extends 'mini_insta/base.html' %}

{% block content %}

<!-- profile information -->
<h1>{{ profile.username }}</h1>
    <profile-detail>
        
        <div>
            <!-- following/followers -->
            <div class="followers-following-container">
                <div class="profile-card">
                    <h3>Followers</h3>
                    <a href="{% url 'show_followers' profile.pk %}" class="update-post-button">
                        {{ profile.get_num_followers }}
                    </a>
                </div>

                <!-- following -->
                <div class="profile-card">
                    <h3>Following</h3>
                    <a href="{% url 'show_following' profile.pk %}" class="update-post-button">
                        {{ profile.get_num_following }}
                    </a>
                </div>

                <!-- if user is logged in and its not their profile -->
                {% if request.user.is_authenticated and request.user != profile.user %}
                    <!-- if already following this user, show unfollow button -->
                    {% if logged_in_profile in profile.get_followers %}

                        <form method="post" action="{% url 'delete_follow' profile.pk %}" class="follow-form">
                            {% csrf_token %}
                            
                            <button type="submit" class="update-post-button unfollow-button">Unfollow</button>
                        </form>

                    <!-- if not, show follow button-->
                    {% else %}

                        <form method="post" action="{% url 'follow' profile.pk %}" class="follow-form">
                            {% csrf_token %}

                            <button type="submit" class="update-post-button follow-button">Follow</button>
                        </form>

                    {% endif %}
                {% endif %}

                
            </div>

            <br>

            <h2>{{ profile.display_name }}</h2>

            
            <p>
                {{ profile.bio_text|linebreaks }}
            </p>


            <p>
                created {{ profile.join_date }}
            </p>
        </div>

        <!-- bigger profile image with interaction :) -->
        <div class="profile-detail-image-container">
            <img src="{{ profile.profile_image_url }}" alt="">
            <img src="https://www.freeiconspng.com/thumbs/blood-splatter-png/blood-splatter-transparent-png-1.png" class="blood-overlay" alt="">
        </div>  

        <!-- button to allow profile updates -->
        {% if request.user.is_authenticated and request.user == profile.user %}
            <div class="profile_update_button">
                <a href="{% url 'update_profile' %}" class="update-post-button">Update this Profile?</a>
            </div>
        {% endif %}
        
    </profile-detail>

    <!-- post displays on the profile -->
    <div class="post-profile">
        <h2>Posts</h2>
        
        <!-- loops through all the posts associated with the profile-->
        {% for post in profile.get_all_posts %}
            <div>
                <!-- id there's an associated photo, display it -->
                {% if post.photo_set.first %}
                <a href="{% url 'show_post' post.pk %}"> 
                    <img src="{{ post.photo_set.first.get_image_url }}" alt="" width="300px">
                </a>
                <!-- otherwise, show a default image -->
                {% else %}
                <a href="{% url 'show_post' post.pk %}"> 
                    <img src="https://upload.wikimedia.org/wikipedia/commons/d/d1/Image_not_available.png" alt="" width="300px">
                </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    
{% endblock %}